[package]
name = "doubletet"
version = "0.1.0"
authors = ["Derek Blankenship <derek@nyghtly.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
